[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.16.0", features = ["train", "wgpu"] }
burn-cuda = "0.16.0"
nannou = "0.19.0"
plotters = "0.3.7"
rand = "0.9.0"
